### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 386: illegal multibyte sequence

### ISSUE THREAD

**Issue by pendave** [amorvincitomnia/vtt-to-srt.py#6]
Error happens when I convet this .vtt file from Vimeo：

> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 386: illegal multibyte sequence

https://vimeo.com/344257719

https://vimeo.com/texttrack/6635743.vtt?token=60653790_0x0b6f5586840480bfdc1ff04a4d2b02f96d72ebc5

Please fix the bug!

I try to change the script line 58 in your vtt_to_srt.py
`    f = open(str_name_file, mode="r", encoding='UTF-8')`

The convertion completes, but when I check the .srt file, the conent in format like

```
00:00:04,110 --> 00:00:06,060
all right so let's just begin with our

00:00:06,060 --> 00:00:09,240
basic bendy limb character and basically

00:00:09,240 --> 00:00:11,610
they have little noodles for arms, dude
```

not a normal format:
```
1
00:00:06,618 --> 00:00:08,742
hi and welcome back to class

2
00:00:08,742 --> 00:00:11,385
2 of Python scripting in Cinema 4D

3
00:00:12,175 --> 00:00:14,512
as this time we're going to follow up

4
00:00:14,527 --> 00:00:16,552
on what we learned in class 1

```

**Comment by amorvincitomnia** [comment]
Please leave a sample file so that I can check if there is a correlation between the encoding you are trying to read and the file.

**Comment by pendave** [comment]
[6635743.zip](https://github.com/jsonzilla/vtt-to-srt.py/files/6498768/6635743.zip)

Here's the .vtt file, thanks.
